// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYfqlMhQt5CV4Pq3Bm07W0P8Zzu_NhKdA',
    appId: '1:28712650524:web:37cb0ad4888f7bb8161cd9',
    messagingSenderId: '28712650524',
    projectId: 'vibzcheck',
    authDomain: 'vibzcheck.firebaseapp.com',
    storageBucket: 'vibzcheck.firebasestorage.app',
    measurementId: 'G-H251X5XX5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIyso6mXgErYSv-PPrH7rtVs1z6tdM350',
    appId: '1:28712650524:android:286aa5721e3ce2bd161cd9',
    messagingSenderId: '28712650524',
    projectId: 'vibzcheck',
    storageBucket: 'vibzcheck.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwcSikQ7PnALQn4P4xRNvT-g6fMDe7Zow',
    appId: '1:28712650524:ios:fe0c2542fa1ad3a2161cd9',
    messagingSenderId: '28712650524',
    projectId: 'vibzcheck',
    storageBucket: 'vibzcheck.firebasestorage.app',
    iosBundleId: 'com.example.vibzcheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwcSikQ7PnALQn4P4xRNvT-g6fMDe7Zow',
    appId: '1:28712650524:ios:fe0c2542fa1ad3a2161cd9',
    messagingSenderId: '28712650524',
    projectId: 'vibzcheck',
    storageBucket: 'vibzcheck.firebasestorage.app',
    iosBundleId: 'com.example.vibzcheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYfqlMhQt5CV4Pq3Bm07W0P8Zzu_NhKdA',
    appId: '1:28712650524:web:84d501e01afbf94d161cd9',
    messagingSenderId: '28712650524',
    projectId: 'vibzcheck',
    authDomain: 'vibzcheck.firebaseapp.com',
    storageBucket: 'vibzcheck.firebasestorage.app',
    measurementId: 'G-3VTETQV8WB',
  );
}
